### PR TITLE
fix: Fixed view headers, moved them into component

### LINKED ISSUE #89: Tissue and Experiment viewer eFP titles
It is only possible to see what the name of the  tissue or experiment view is by mousing over the thumbnail. Title should also be present in the view itself...might need to move expression level indicator to another location?

Also, there are some rendering issues of SVG elements in dark mode in several tissue and experiment views.

image

### PR DESCRIPTION
**Pull request by Yukthiw**
Moved header out of view interface and into view component

### CODE REVIEW

File: Eplant/views/eFP/Viewer/index.tsx [hunk 1]
```diff
@@ -252,18 +252,25 @@ export default class EFPViewer
...
-            colorMode: state.colorMode,
-            renderAsThumbnail: false,
-            maskThreshold: state.maskThreshold,
-          }}
-          geneticElement={geneticElement}
-          dispatch={() => {}}
-        />
+        <>
+          <Typography variant='h6'>
+            {activeData.views.find((v) => v.id == state.activeView)?.name}
```
Comment (zkdan) [inline Eplant/views/eFP/Viewer/index.tsx]: Use `===` over `==`; triple equals compares type and value, double only compares value.

**Review by zkdan — CHANGES_REQUESTED** [review]

**Review by zkdan — APPROVED** [review]
