### PR TITLE
fix: Changed mask modal to be a toggle, increased max masking % to 200%

### LINKED ISSUE #103: Add Toggle to eFP Masking
At the present moment, eFP masking is always active and set to 100%. This should instead be a toggle. When toggled off, no masking should occur, when toggled on the Mask Modal should appear and allow you to set the mask threshold. The maximum mask threshold should also be raised to 200% (default still at 100%)

In ePlant 2 example of masking being toggled off:

image

Example of masking being toggled on:

image

### PR DESCRIPTION
**Pull request by Yukthiw**

### CODE REVIEW

File: Eplant/views/eFP/index.tsx [hunk 1]
```diff
@@ -191,7 +192,8 @@ export default class EFP implements View<EFPData, EFPState, EFPAction> {
       id,
       props.activeData,
       props.state.colorMode,
-      props.state.maskThreshold
+      props.state.maskThreshold,
+      props.state.maskingEnabled
```
Comment (zkdan) [inline Eplant/views/eFP/index.tsx]: destruc

File: Eplant/views/eFP/Viewer/index.tsx [hunk 2]
```diff
@@ -88,7 +90,9 @@ const EFPListItem = memo(
       prev.data.colorMode === next.data.colorMode &&
       prev.data.geneticElement.id === next.data.geneticElement.id &&
       prev.data.activeView === next.data.activeView &&
-      prev.index == next.index
+      prev.index == next.index &&
```
Comment (zkdan) [inline Eplant/views/eFP/Viewer/index.tsx:93]: === over ==

**Review by zkdan — APPROVED** [review]
